spring.application.name=system
# PostgreSQL Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/voting_system
spring.datasource.username=leraa
spring.datasource.password=leraa

# Hibernate / JPA Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ddl-auto: update creates/updates tables automatically from @Entity classes
spring.jpa.hibernate.ddl-auto=update

# Show executed SQL queries in terminal logs
spring.jpa.show-sql=true